services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 40s ; python ./app.py"
    depends_on:
      - mysql
 
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'product'
      MYSQL_ROOT_PASSWORD: '*********'
    ports:mysql-python-flaskapp/ 
      - '8081:3306'